// Generated by CoffeeScript 1.8.0

/*
  BmwController (Orientation + Gas Pedal) for BMW i3 Input

  @class bkcore.BmwController
  @author Frank Blechschmidt <http://twitter.com/frable90>
 */
var BmwController, exports, _base;

BmwController = (function() {
  BmwController.isCompatible = function() {
    return 'bmwConnector' in navigator;
  };


  /*
    Creates a new BmwController
   */

  function BmwController(actionCallback) {
    this.actionCallback = actionCallback;
    this.active = true;
  }


  /*
    @public
   */

  BmwController.prototype.updateAvailable = function() {
    var bmwConnector;
    bmwConnector = navigator.bmwConnector;
    if (!this.active || !bmwConnector) {
      return false;
    }
    this.steeringAngle = bmwConnector.steeringAngle / 100;
    console.log(bmwConnector.steeringAngle);
    this.accelerationPedal = bmwConnector.accelerationPedal / 100;
    this.actionCallback(this);
    return true;
  };

  return BmwController;

})();

exports = exports != null ? exports : this;

exports.bkcore || (exports.bkcore = {});

(_base = exports.bkcore).controllers || (_base.controllers = {});

exports.bkcore.controllers.BmwController = BmwController;

//# sourceMappingURL=BmwController.js.map
