// Generated by CoffeeScript 1.10.0

/*
  GamepadController (Orientation + buttons) for touch devices

  @class bkcore.GamepadController
  @author Mahesh Kulkarni <http://twitter.com/maheshkk>
 */

(function() {
  var GamepadController, base, exports;

  GamepadController = (function() {
    GamepadController.isCompatible = function() {
      return ('getGamepads' in navigator) || ('webkitGetGamepads' in navigator);
    };


    /*
      Creates a new GamepadController
     */

    function GamepadController(buttonPressCallback) {
      this.buttonPressCallback = buttonPressCallback;
      this.active = true;
      this.leftStickArray = [];
      this.rightStickArray = [];
    }


    /*
      @public
     */

    GamepadController.prototype.updateAvailable = function() {
      var accel, gamepads, gp, lt, pad, ref, ref1, ref2, ref3, rt, sel;
      if (!this.active) {
        return false;
      }
      gamepads = navigator.getGamepads ? navigator.getGamepads() : navigator.webkitGetGamepads();
      if (!gamepads) {
        return false;
      }
      gp = ((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = gamepads.length; i < len; i++) {
          pad = gamepads[i];
          if ((pad != null ? pad.mapping : void 0) === 'standard') {
            results.push(pad);
          }
        }
        return results;
      })())[0];
      if (((gp != null ? gp.buttons : void 0) == null) || (gp.axes == null)) {
        return;
      }
      this.lstickx = gp.axes[0];
      accel = gp.buttons[0];
      lt = gp.buttons[6];
      rt = gp.buttons[7];
      sel = gp.buttons[8];
      this.acceleration = (ref = accel.pressed) != null ? ref : accel;
      this.ltrigger = (ref1 = lt.pressed) != null ? ref1 : lt;
      this.rtrigger = (ref2 = rt.pressed) != null ? ref2 : rt;
      this.select = (ref3 = sel.pressed) != null ? ref3 : sel;
      this.buttonPressCallback(this);
      return true;
    };

    return GamepadController;

  })();

  exports = exports != null ? exports : this;

  exports.bkcore || (exports.bkcore = {});

  (base = exports.bkcore).controllers || (base.controllers = {});

  exports.bkcore.controllers.GamepadController = GamepadController;

}).call(this);
